### ISSUE TITLE
up and down

### ISSUE THREAD

**Issue by diomed** [ispal/vue-chevron#1]
hello

what do you think about creating example with chevron
that automatically changes to up `^` or down `v` depending on 
where it is located on the page, like it's in half top of the page it would 
point to down and have ability to slide to down, but once it passes it, 
it changes back to `^` scroll to top.
if this is feasible

**Comment by ispal** [comment]
Hi,

I don't have time to do it currently, but there are plenty of libraries that helps you with the scroll position so I suggest you look into those. I have plans to create some demos for vuetify, bootstrap etc., but I can't give any timespan when those would be available.
